import * as v from "valibot";

import { EnvSchema } from "@/shared/validations/schemas/EnvSchema";

export type ShackwEnv = v.InferOutput<typeof EnvSchema>;

export const ENV: ShackwEnv = v.parse(EnvSchema, {
  DATABASE_VERSION: process.env.EXPO_PUBLIC_DATABASE_VERSION,
  WALLET_PRIVATE_KEY_BASE_NAME: process.env.EXPO_PUBLIC_WALLET_PRIVATE_KEY_BASE_NAME,

  RPC_INFURA_ID: process.env.EXPO_PUBLIC_RPC_INFURA_ID,
  SHACKW_API_URL: process.env.EXPO_PUBLIC_SHACKW_API_URL,
  SHACKW_UNIVERSAL_LINK: process.env.EXPO_PUBLIC_SHACKW_UNIVERSAL_LINK,

  ETH_MAIN_JPYC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_ETH_MAIN_JPYC_TOKEN_ADDRESS,
  ETH_MAIN_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_ETH_MAIN_USDC_TOKEN_ADDRESS,
  ETH_MAIN_EURC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_ETH_MAIN_EURC_TOKEN_ADDRESS,

  ETH_SEPOLIA_JPYC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_ETH_SEPOLIA_JPYC_TOKEN_ADDRESS,
  ETH_SEPOLIA_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_ETH_SEPOLIA_USDC_TOKEN_ADDRESS,
  ETH_SEPOLIA_EURC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_ETH_SEPOLIA_EURC_TOKEN_ADDRESS,

  BASE_MAIN_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_MAIN_USDC_TOKEN_ADDRESS,
  BASE_MAIN_EURC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_MAIN_EURC_TOKEN_ADDRESS,

  BASE_SEPOLIA_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_SEPOLIA_USDC_TOKEN_ADDRESS,
  BASE_SEPOLIA_EURC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_SEPOLIA_EURC_TOKEN_ADDRESS,

  POLYGON_MAIN_JPYC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_POLYGON_MAIN_JPYC_TOKEN_ADDRESS,
  POLYGON_MAIN_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_POLYGON_MAIN_USDC_TOKEN_ADDRESS,

  POLYGON_AMOY_JPYC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_POLYGON_AMOY_JPYC_TOKEN_ADDRESS,
  POLYGON_AMOY_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_POLYGON_AMOY_USDC_TOKEN_ADDRESS
});
