import * as v from "valibot";

import { EnvSchema } from "@/shared/validations/schemas/EnvSchema";

export type ShackwEnv = v.InferOutput<typeof EnvSchema>;
export type BuildEnv = ShackwEnv["BUILD_ENV"];

export const ENV: ShackwEnv = v.parse(EnvSchema, {
  BUILD_ENV: process.env.EXPO_PUBLIC_BUILD_ENV,

  DATABASE_VERSION: process.env.EXPO_PUBLIC_DATABASE_VERSION,
  WALLET_PRIVATE_KEY_BASE_NAME: process.env.EXPO_PUBLIC_WALLET_PRIVATE_KEY_BASE_NAME,

  RPC_INFURA_ID: process.env.EXPO_PUBLIC_RPC_INFURA_ID,
  SHACKW_API_URL: process.env.EXPO_PUBLIC_SHACKW_API_URL,
  SHACKW_UNIVERSAL_LINK: process.env.EXPO_PUBLIC_SHACKW_UNIVERSAL_LINK,

  MAIN_JPYC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_MAIN_JPYC_TOKEN_ADDRESS,
  MAIN_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_MAIN_USDC_TOKEN_ADDRESS,
  MAIN_EURC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_MAIN_EURC_TOKEN_ADDRESS,

  BASE_JPYC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_JPYC_TOKEN_ADDRESS,
  BASE_USDC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_USDC_TOKEN_ADDRESS,
  BASE_EURC_TOKEN_ADDRESS: process.env.EXPO_PUBLIC_BASE_EURC_TOKEN_ADDRESS
});
